name: profile_site
description: My Flutter projects.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  animated_flight_paths: ^0.0.3
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  lottie: ^2.4.0
  riverpod_annotation: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.11
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/me/
    - assets/images/brands/
    - assets/images/logos/
    - assets/images/projects/
    - assets/lotties/
    - assets/fonts/
